# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_INV_ICM20948) += inv-icm20948.o
inv-icm20948-y += inv_icm20948_core.o
inv-icm20948-y += inv_icm20948_temp.o
inv-icm20948-y += inv_icm20948_gyro.o
inv-icm20948-y += inv_icm20948_accel.o
inv-icm20948-y += inv_icm20948_magn.o
inv-icm20948-y += inv_icm20948_power.o

obj-$(CONFIG_INV_ICM20948_I2C) += inv-icm20948-i2c.o
inv-icm20948-i2c-y += inv_icm20948_i2c.o

obj-$(CONFIG_INV_ICM20948_SPI) += inv-icm20948-spi.o
inv-icm20948-spi-y += inv_icm20948_spi.o
